
/*
 * Copyright (C) Zhefeng Chen
 */


#ifndef _NGX_STREAM_FPROXY_H_INCLUDED_
#define _NGX_STREAM_FPROXY_H_INCLUDED_


#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_stream.h>



typedef enum {
    NGX_STREAM_FPROXY_TYPE_HTTP = 0,
    NGX_STREAM_FPROXY_TYPE_HTTPS,
    NGX_STREAM_FPROXY_TYPE_SOCKS5
} NGX_STREAM_FPROXY_TYPE; 

typedef enum {
    NGX_STREAM_FPROXY_STATE_START = 0,
    NGX_STREAM_FPROXY_STATE_GREETING,
    NGX_STREAM_FPROXY_STATE_SOCKS5_METHOD_SELECT,
    NGX_STREAM_FPROXY_STATE_SOCKS5_METHOD_ACCEPTED,
    NGX_STREAM_FPROXY_STATE_SOCKS5_AUTH_REQUEST,
    NGX_STREAM_FPROXY_STATE_SOCKS5_AUTH_RESPONSE,
    NGX_STREAM_FPROXY_STATE_SOCKS5_REQUEST,
    NGX_STREAM_FPROXY_STATE_SOCKS5_RESOLVING,
    NGX_STREAM_FPROXY_STATE_SOCKS5_CONNECT_UPSTREAM,
    NGX_STREAM_FPROXY_STATE_SOCKS5_REPLY,
    NGX_STREAM_FPROXY_STATE_SOCKS5_FAIL_REPLY,
    NGX_STREAM_FPROXY_STATE_SOCKS5_PROXYING,
    NGX_STREAM_FPROXY_STATE_HTTP_REQUEST_LINE,
    NGX_STREAM_FPROXY_STATE_HTTP_REQUEST_HEADERS,
    NGX_STREAM_FPROXY_STATE_HTTP_AUTH,
    NGX_STREAM_FPROXY_STATE_HTTP_RESOLVING,
    NGX_STREAM_FPROXY_STATE_HTTP_CONNECT_UPSTREAM,
    NGX_STREAM_FPROXY_STATE_HTTP_RESPONSE, /* CONNECT only */
    NGX_STREAM_FPROXY_STATE_HTTP_FAIL_RESPONSE,
    NGX_STREAM_FPROXY_STATE_HTTP_PROXYING,
} NGX_STREAM_FPROXY_STATE;

#define NGX_STREAM_FPROXY_PROTOCOL_HTTP     0x0002
#define NGX_STREAM_FPROXY_PROTOCOL_SOCKS5   0x0004

#define NGX_STREAM_FPROXY_AUTH_NONE         0x0000
#define NGX_STREAM_FPROXY_AUTH_BASIC        0x0002

/* additional rc */
#define NGX_STREAM_AUTH_OK                  600
#define NGX_STREAM_METHOD_ACCEPTED          601
#define NGX_STREAM_METHOD_NO_ACCEPT         700

#define NGX_STREAM_FPROXY_SOCKS5_VERSION            0x05
#define NGX_STREAM_FPROXY_SOCKS5_BASIC_VERSION      0x01

#define NGX_STREAM_FPROXY_SOCKS5_AUTH_NO_AUTH       0x00
#define NGX_STREAM_FPROXY_SOCKS5_AUTH_GSSAPI        0x01
#define NGX_STREAM_FPROXY_SOCKS5_AUTH_BASIC         0x02
#define NGX_STREAM_FPROXY_SOCKS5_AUTH_NO_ACCEPT     0xff

#define NGX_STREAM_FPROXY_SOCKS5_AUTH_SUCCESS       0x00
#define NGX_STREAM_FPROXY_SOCKS5_AUTH_FAILURE       0x01

#define NGX_STREAM_FPROXY_SOCKS5_REPLY_SUCCEEDED            0x00
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_SERVER_FAILURE       0x01
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_RULESET_DENIED       0x02
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_NETWORK_UNREACHABLE  0x03
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_HOST_UNREACHABLE     0x04
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_CONNECTION_REFUSED   0x05
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_TTL_EXPIRED          0x06
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_COMMAND_UNSUPPORTED  0x07
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_ATYPE_UNSUPPORTED    0x08
#define NGX_STREAM_FPROXY_SOCKS5_REPLY_BAD_REQUEST          0x09

#define NGX_STREAM_FPROXY_SOCKS5_ATYPE_IPV4         0x01
#define NGX_STREAM_FPROXY_SOCKS5_ATYPE_DOMAIN       0x03
#define NGX_STREAM_FPROXY_SOCKS5_ATYPE_IPV6         0x04

#define NGX_STREAM_FPROXY_SOCKS5_CMD_CONNECT        0x01
#define NGX_STREAM_FPROXY_SOCKS5_CMD_BIND           0x02
#define NGX_STREAM_FPROXY_SOCKS5_CMD_UDP            0x03

extern ngx_module_t  ngx_stream_fproxy_module;

#endif /* _NGX_STREAM_FPROXY_H_INCLUDED_ */
